# Generated by Django 4.2.30 on 2026-06-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='唱段名称')),
                ('lyrics', models.TextField(blank=True, verbose_name='歌词')),
                ('order_index', models.IntegerField(verbose_name='演出顺序')),
                ('duration', models.IntegerField(help_text='秒', verbose_name='唱段时长')),
                ('role_type', models.CharField(choices=[('sheng', '生'), ('dan', '旦'), ('jing', '净'), ('mo', '末'), ('chou', '丑')], max_length=20, verbose_name='行当')),
                ('accompaniment_required', models.TextField(blank=True, verbose_name='伴奏需求')),
            ],
            options={
                'verbose_name': '唱段',
                'verbose_name_plural': '唱段',
                'ordering': ['program', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='AriaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_understudy', models.BooleanField(default=False, verbose_name='是否替补')),
                ('status', models.CharField(choices=[('confirmed', '确认'), ('pending', '待确认'), ('rejected', '拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('aria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='opera.aria', verbose_name='唱段')),
            ],
            options={
                'verbose_name': '唱段分配',
                'verbose_name_plural': '唱段分配',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('role_types', models.CharField(max_length=100, verbose_name='擅长行当')),
                ('available_times', models.JSONField(default=dict, verbose_name='可排练时段')),
                ('is_understudy', models.BooleanField(default=False, verbose_name='是否愿意替补')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='节目名称')),
                ('description', models.TextField(blank=True, verbose_name='节目描述')),
                ('type', models.CharField(choices=[('beijing', '京剧'), ('henan', '豫剧'), ('kunqu', '昆曲'), ('yue', '越剧'), ('huangmei', '黄梅戏'), ('other', '其他')], default='beijing', max_length=20, verbose_name='剧种')),
                ('duration', models.IntegerField(help_text='分钟', verbose_name='总时长')),
                ('status', models.CharField(choices=[('planning', '筹备'), ('rehearsing', '排练'), ('performing', '演出'), ('archived', '归档')], default='planning', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '节目',
                'verbose_name_plural': '节目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='排练日期')),
                ('location', models.CharField(max_length=200, verbose_name='排练地点')),
                ('notes', models.TextField(blank=True, verbose_name='排练备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='opera.program', verbose_name='所属节目')),
            ],
            options={
                'verbose_name': '排练记录',
                'verbose_name_plural': '排练记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UnderstudyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='调整原因')),
                ('date', models.DateField(verbose_name='调整日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='understudy_changes', to='opera.ariaassignment', verbose_name='原分配')),
                ('substitute_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_changes', to='opera.member', verbose_name='替补成员')),
            ],
            options={
                'verbose_name': '替补调整记录',
                'verbose_name_plural': '替补调整记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('role_type', models.CharField(choices=[('sheng', '生'), ('dan', '旦'), ('jing', '净'), ('mo', '末'), ('chou', '丑')], max_length=20, verbose_name='行当')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='opera.program', verbose_name='所属节目')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['program', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(blank=True, verbose_name='录音链接')),
                ('start_beat_issue', models.TextField(blank=True, verbose_name='起板问题')),
                ('forgotten_lines', models.TextField(blank=True, verbose_name='忘词片段')),
                ('teacher_comments', models.TextField(blank=True, verbose_name='老师点评')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('aria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='opera.aria', verbose_name='唱段')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='opera.member', verbose_name='成员')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='opera.rehearsal', verbose_name='排练记录')),
            ],
            options={
                'verbose_name': '排练反馈',
                'verbose_name_plural': '排练反馈',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ariaassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='opera.member', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='ariaassignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='opera.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='aria',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arias', to='opera.program', verbose_name='所属节目'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('final_assignments', models.JSONField(default=dict, verbose_name='最终分配记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='归档时间')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='opera.program', verbose_name='所属节目')),
            ],
            options={
                'verbose_name': '版本归档',
                'verbose_name_plural': '版本归档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aria',
            unique_together={('program', 'order_index')},
        ),
    ]
