# Generated by Django 4.2.30 on 2026-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='understudychange',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('completed', '已完成'), ('cancelled', '已取消'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
