# Generated by Django 4.2.30 on 2026-06-18 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0002_add_rejected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='批次名称')),
                ('planned_performance_date', models.DateField(blank=True, null=True, verbose_name='计划演出日期')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_checks', to='opera.program', verbose_name='所属节目')),
            ],
            options={
                'verbose_name': '联排确认批次',
                'verbose_name_plural': '联排确认批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(verbose_name='唱段顺序快照')),
                ('role_type', models.CharField(choices=[('sheng', '生'), ('dan', '旦'), ('jing', '净'), ('mo', '末'), ('chou', '丑')], max_length=20, verbose_name='行当快照')),
                ('accompaniment_required', models.TextField(blank=True, verbose_name='伴奏需求快照')),
                ('accompaniment_confirmed', models.BooleanField(default=False, verbose_name='伴奏已备齐')),
                ('risk_level', models.CharField(choices=[('none', '无风险'), ('low', '低'), ('medium', '中'), ('high', '高')], default='none', max_length=20, verbose_name='风险等级')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='处理意见')),
                ('risk_action_created', models.BooleanField(default=False, verbose_name='已生成待处理项')),
                ('latest_feedback_date', models.DateField(blank=True, null=True, verbose_name='最近反馈日期')),
                ('latest_start_beat_issue', models.TextField(blank=True, verbose_name='最近起板问题')),
                ('latest_forgotten_lines', models.TextField(blank=True, verbose_name='最近忘词片段')),
                ('latest_teacher_comments', models.TextField(blank=True, verbose_name='最近老师点评')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('accompaniment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompaniment_confirmations', to='opera.member', verbose_name='伴奏确认人')),
                ('aria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_check_items', to='opera.aria', verbose_name='唱段')),
                ('rehearsal_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='opera.rehearsalcheck', verbose_name='联排批次')),
            ],
            options={
                'verbose_name': '联排确认清单项',
                'verbose_name_plural': '联排确认清单项',
                'ordering': ['rehearsal_check', 'order_index'],
                'unique_together': {('rehearsal_check', 'aria')},
            },
        ),
        migrations.CreateModel(
            name='RiskActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('attendance', '未确认到场'), ('understudy', '无替补'), ('feedback', '排练反馈问题'), ('accompaniment', '伴奏未确认'), ('teacher_risk', '老师标注风险')], max_length=20, verbose_name='待处理类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_actions', to='opera.rehearsalcheckitem', verbose_name='清单项')),
            ],
            options={
                'verbose_name': '风险待处理项',
                'verbose_name_plural': '风险待处理项',
                'ordering': ['-created_at'],
                'unique_together': {('check_item', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='RehearsalCheckConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_understudy', models.BooleanField(default=False, verbose_name='是否替补')),
                ('attendance_confirmed', models.BooleanField(default=False, verbose_name='到场确认')),
                ('lyrics_proficiency', models.CharField(choices=[('unconfirmed', '未确认'), ('familiar', '熟练'), ('needs_practice', '需练习')], default='unconfirmed', max_length=20, verbose_name='歌词熟练度')),
                ('needs_understudy_help', models.BooleanField(default=False, verbose_name='需要替补协助')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='opera.rehearsalcheckitem', verbose_name='清单项')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_confirmations', to='opera.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '联排确认记录',
                'verbose_name_plural': '联排确认记录',
                'ordering': ['check_item', 'is_understudy', 'id'],
                'unique_together': {('check_item', 'member')},
            },
        ),
    ]
