# Generated by Django 4.2.30 on 2026-06-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0003_rehearsal_check_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsalcheckconfirmation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsal_confirmations', to='opera.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='rehearsalcheckconfirmation',
            name='role_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='角色名称快照'),
        ),
    ]
