# Generated by Django 4.2.30 on 2026-06-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0004_rehearsalcheckconfirmation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskactionitem',
            name='auto_resolve_pending',
            field=models.BooleanField(default=False, verbose_name='待管理员确认解除'),
        ),
        migrations.AddField(
            model_name='riskactionitem',
            name='auto_resolve_suggested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='建议解除时间'),
        ),
        migrations.AddField(
            model_name='riskactionitem',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_risk_actions', to='opera.member', verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='riskactionitem',
            name='handler_note',
            field=models.TextField(blank=True, verbose_name='处理备注'),
        ),
        migrations.AddField(
            model_name='riskactionitem',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近复核时间'),
        ),
        migrations.AddField(
            model_name='riskactionitem',
            name='latest_reason',
            field=models.TextField(blank=True, verbose_name='最新风险原因'),
        ),
        migrations.AddField(
            model_name='riskactionitem',
            name='resolution_source',
            field=models.CharField(blank=True, choices=[('attendance_confirm', '成员到场确认'), ('lyrics_update', '歌词熟练度更新'), ('accompaniment_confirm', '伴奏确认'), ('teacher_risk_adjust', '老师风险等级调整'), ('feedback_clear', '排练反馈问题清除'), ('understudy_add', '替补成员添加'), ('manual_close', '管理员手动处理'), ('system_auto', '系统自动复核')], max_length=30, null=True, verbose_name='解除来源'),
        ),
        migrations.AlterField(
            model_name='riskactionitem',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('auto_resolved', '自动解除'), ('manually_resolved', '手动解除'), ('confirmed_closed', '管理员确认关闭')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
