# Generated by Django 4.2.30 on 2026-06-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opera', '0005_riskactionitem_auto_resolve_pending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='复盘批次名称')),
                ('performance_date', models.DateField(verbose_name='演出日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('teacher_reviewing', '老师复盘中'), ('member_reviewing', '成员自评中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('actual_performance_note', models.TextField(blank=True, verbose_name='实际演出备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews', to='opera.archive', verbose_name='关联归档版本')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='opera.program', verbose_name='所属节目')),
            ],
            options={
                'verbose_name': '演出复盘批次',
                'verbose_name_plural': '演出复盘批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(verbose_name='唱段顺序快照')),
                ('role_type', models.CharField(choices=[('sheng', '生'), ('dan', '旦'), ('jing', '净'), ('mo', '末'), ('chou', '丑')], max_length=20, verbose_name='行当快照')),
                ('final_assignments', models.JSONField(default=list, verbose_name='最终分配快照')),
                ('rehearsal_check_summary', models.JSONField(default=dict, verbose_name='联排确认汇总')),
                ('risk_record_summary', models.JSONField(default=list, verbose_name='风险处理记录汇总')),
                ('rehearsal_feedback_summary', models.JSONField(default=list, verbose_name='排练反馈汇总')),
                ('understudy_record_summary', models.JSONField(default=list, verbose_name='替补发生记录汇总')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('aria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='opera.aria', verbose_name='唱段')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='opera.performancereview', verbose_name='复盘批次')),
            ],
            options={
                'verbose_name': '复盘清单项',
                'verbose_name_plural': '复盘清单项',
                'ordering': ['review', 'order_index'],
                'unique_together': {('review', 'aria')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_performance', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('average', '一般'), ('needs_improvement', '需改进')], default='good', max_length=20, verbose_name='舞台表现')),
                ('rhythm_stability', models.CharField(choices=[('stable', '稳定'), ('mostly_stable', '基本稳定'), ('unstable', '不稳定')], default='mostly_stable', max_length=20, verbose_name='节奏稳定性')),
                ('forgotten_lines', models.TextField(blank=True, verbose_name='忘词问题')),
                ('beat_issues', models.TextField(blank=True, verbose_name='抢板/掉板问题')),
                ('accompaniment_cohesion', models.TextField(blank=True, verbose_name='伴奏衔接问题')),
                ('overall_comment', models.TextField(blank=True, verbose_name='整体点评')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='改进建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='opera.performancereviewitem', verbose_name='复盘清单项')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_reviews', to='opera.member', verbose_name='点评老师')),
            ],
            options={
                'verbose_name': '复盘结论',
                'verbose_name_plural': '复盘结论',
                'ordering': ['review_item', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('risk', '未解决风险'), ('performance_issue', '演出中暴露问题'), ('teacher_suggestion', '老师改进建议'), ('self_goal', '个人改进目标')], max_length=20, verbose_name='来源类型')),
                ('source_description', models.TextField(verbose_name='来源描述')),
                ('task_title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('task_description', models.TextField(blank=True, verbose_name='任务描述')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止时间')),
                ('completion_note', models.TextField(blank=True, verbose_name='完成备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_improvement_tasks', to='opera.member', verbose_name='责任人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_improvement_tasks', to='opera.member', verbose_name='创建人')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_tasks', to='opera.performancereview', verbose_name='复盘批次')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_tasks', to='opera.performancereviewitem', verbose_name='关联清单项')),
            ],
            options={
                'verbose_name': '改进训练任务',
                'verbose_name_plural': '改进训练任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberSelfReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.IntegerField(default=3, verbose_name='自评分数(1-5)')),
                ('self_comment', models.TextField(blank=True, verbose_name='自我评语')),
                ('improvement_goal', models.TextField(blank=True, verbose_name='下次改进目标')),
                ('highlights', models.TextField(blank=True, verbose_name='本场亮点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reviews', to='opera.member', verbose_name='成员')),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reviews', to='opera.performancereviewitem', verbose_name='复盘清单项')),
            ],
            options={
                'verbose_name': '成员自评',
                'verbose_name_plural': '成员自评',
                'ordering': ['review_item', 'member'],
                'unique_together': {('review_item', 'member')},
            },
        ),
    ]
